# Project Euler Question 45
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle : T(n) = n*(n+1)/2
# Pentagonal : P(n) = n*(3n-1)/2
# Hexagonal : H(n) = n*(2n-1)
# It can be verified that T(285) = P(165) = H(143) = 40755
# Find the next triangle number that is also pentagonal and hexagonal.

import numpy


def triangle_gen(n):
    return n*(n+1)/2


def triangle_pentagon(n):
    temp = 1 + numpy.sqrt(1+triangle_gen(n)*24)
    if temp % 6 == 0:
        return True
    else:
        return False


def triangle_hexagon(n):
    temp = 1 + numpy.sqrt(1+triangle_gen(n)*8)
    if temp % 4 == 0:
        return True
    else:
        return False


count = 286

while triangle_pentagon(count) != True:
    count += 1

if triangle_hexagon(count) == True:
    print(count)
else:
    count += 1



